---
- hosts: all
  become: yes
  roles:
    - role: insight_infra.cloud_helper
      vars:
        enable_cloud_wait: true
        enable_jq: true
    - node-exporter
    - insight_infra.polkadot_library
    - insight_infra.polkadot_health_check